[opener]
system_default = [
    { run = 'xdg-open "$1"', desc = "System Default", for = "linux" }
]
edit = [
    { run = "$EDITOR %s", block = true, for = "unix" },
]
open = [
    { run = 'xdg-open "$@"', desc = "Open" }
]
# imv = [
#     { run = 'imv "$@"', block = true, desc = "imv" }
# ]

[open]
prepend_rules = [
	{ url = "*.json", use = "edit" },
	{ url = "*.kdl", use = "edit" },
	# { url = "*lua", use = "edit" },
	{ url = "*yml", use = "edit" },

	# Multiple openers for a single rule
	{ url = "*.html", use = [ "open", "edit" ] },

  { mime = "application/pdf", use = [ "system_default" ] },
  { mime = "image/*", use = [  "system_default" ] },
  { mime = "{audio,video}/*", use = [ "system_default" ] }
]

append_rules = [
	{ url = "*", use = ["open", "edit"] },
]



[mgr]
show_hidden = true

# [plugin]
# prepend_previewers = [
#     { mime = "image/*", run = "imv-preview" }
# ]
